### ISSUE TITLE
not compatible with graph search

### ISSUE THREAD

**Issue by revarcline** [dtinth/dark-facebook#2]
Any word on possibly making this compatible with Graph Search? This theme is great, but I can't use it (or most other themes) with the header changed...

**Comment by dtinth** [comment]
Can you attach the screenshot of new header? I also have Graph Search, but don't have problem with the header.

**Comment by revarcline** [comment]
Here it is - my useragent is Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:23.0) Gecko/20100101 Firefox/23.0 and I'm running the latest version of the script from userstyles.org. The behavior was consistent in using it through greasemonkey, stylish, and social fixer.

![brokenfbdark](https://f.cloud.github.com/assets/4873319/1021960/3489d2f2-0d49-11e3-839f-b803f5db47f3.png)

**Comment by revarcline** [comment]
Note that the facebook logo and the friend request/messages/notification icons are all wrong, as well as the status icons in the chat sidebar.

**Comment by dtinth** [comment]
Tge theme somehow triggered Facebook's High-Contrast mode. I'll have to
look deeper to find solution to prevent high contrast mode.

Thanks for your report!

**Comment by revarcline** [comment]
So I found this theme works http://userstyles.org/styles/65379/faceblack I
just don't care for it because it is all shiny. Honestly I was hoping yours
would work because it would be a good starting point to make my own zenburn
fb, lol

**Comment by dtinth** [comment]
Zenburn Fb? Wow, really nice idea!

Right now, the theme triggered "high contrast" mode because of the theming approach. This userstyle resets the backgrounds, borders and everything. I've yet to find a solution to this, unfortunately.

The source code, right now, is also a mess.

I had a plan long ago to recreate this theme from scratch (maybe using CoffeeScript instead of Stylus, in a way that totally separates the "style definition" (CSS code) from CSS selectors, because Facebook changes CSS so often), without having to override all elements first.
