### ISSUE TITLE
Applying theme in social fixer no longer works

### ISSUE THREAD

**Issue by awestpantek** [dtinth/dark-facebook#55]
This theme suddenly quit working for me today, I tried to reapply the theme but no colors are changed. The midnight theme also suffers the same issue. All of the other themes available in social fixer seem to work.

**Comment by dtinth** [comment]
Please see the [wiki on Troubleshooting: Theme Stops Working Completely on Social Fixer](https://github.com/dtinth/dark-facebook/wiki/Troubleshooting:-Theme-Stops-Working-Completely-on-Social-Fixer).

Since this is a very common issue, I'll close it for now. If these solutions in the wiki doesn't work, please reopen this issue.
