### ISSUE TITLE
Theme not loading.

### ISSUE THREAD

**Issue by overfiend1976** [dtinth/dark-facebook#56]
Checked all other themes, they're fine, however, this one will not load at all.

**Comment by dtinth** [comment]
Please see the [wiki on Troubleshooting: Theme Stops Working Completely on Social Fixer](https://github.com/dtinth/dark-facebook/wiki/Troubleshooting:-Theme-Stops-Working-Completely-on-Social-Fixer).

Since this is a very common issue, I'll close it for now. If these solutions in the wiki doesn't work, please reopen this issue.

**Comment by overfiend1976** [comment]
The CSS code worked. I used to have it there, no idea why social fixer ate
it on me.

On Wed, Dec 17, 2014 at 3:38 AM, Thai Pangsakulyanont <
notifications@github.com> wrote:

> Please see the wiki on Troubleshooting: Theme Stops Working Completely on
> Social Fixer
> https://github.com/dtinth/dark-facebook/wiki/Troubleshooting:-Theme-Stops-Working-Completely-on-Social-Fixer
> .
> 
> Since this is a very common issue, I'll close it for now. If these
> solutions in the wiki doesn't work, please reopen this issue.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/dtinth/dark-facebook/issues/56#issuecomment-67298000.

## 

This signature will self-destruct in 5 seconds.
